config/routes.rb
Rails.application.routes.draw do
  get 'current_user/index'
  
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  root "home#index"
  get "/about", to: "static_pages#about", as: :about
  get "/blog", to: "static_pages#blog"
  get "/contacts", to: "static_pages#contacts"
  get "/services", to: "static_pages#services"
  get '/services/product_filter_service', to: 'product_filter_service#filter'
  get 'profile', to: 'profiles#show', as: :user_profile
  get 'profile_updated', to: 'profiles#updated', as: :profile_updated
  get 'add_to_cart/:product_id', to: 'orders#create', as: 'add_to_cart'
  get 'cart', to: 'orders#cart'
  post 'complete_order', to: 'orders#complete_order', as: 'complete_order'
  get 'completed_orders', to: 'orders#completed_orders', as: 'completed_orders'
  get "orders_page", to: "orders#orders_page", as: "orders_page"
  get 'admin/orders', to: 'admin#orders', as: 'admin_orders'
  
  resources :orders, only: [:show] do
    collection do
      delete 'remove_from_cart/:order_item_id', action: :remove_from_cart, as: :remove_from_cart
    end
  end

  resources :products
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :orders do
    member do
      patch :handle, to: 'orders#handle'
    end
  end

  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: { registrations: 'api/v1/users/registrations', sessions: 'api/v1/users/sessions' }    
      resources :products
      resources :profiles, only: [:new, :create, :edit, :update]
      resources :orders do
        member do
          patch :handle, to: 'orders#handle'
          post :remove_from_cart, to: 'orders#remove_from_cart'
          post :complete_order, to: "orders@complete_orders"
        end
      end
      resources :admin do
        collection do
          get :all_users
        end
      end
      get '/services/product_filter_service', to: 'product_filter_service#filter'
      get 'profile', to: 'profiles#show', as: :user_profile
      get 'profile/new', to: "profiles#new", as: "new_profile"
      get 'profile_updated', to: 'profiles#updated', as: :profile_updated
      post 'add_to_cart', to: 'orders#create', as: 'add_to_cart'
      get 'cart', to: 'orders#cart'
      post 'complete_order', to: 'orders#complete_order', as: 'complete_order'
      get 'completed_orders', to: 'orders#completed_orders', as: 'completed_orders'
      get "orders_page", to: "orders#orders_page", as: "orders_page"
      get 'admin/orders', to: 'admin#orders', as: 'admin_orders'
      root "home#index"
    end
  end


end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: true
  validates :last_name,  presence: true
  validates :phone,      presence: true

end

app/controllers/api/v1/profiles_controller.rb
class Api::V1::ProfilesController < Api::V1::ApplicationController
  before_action :authenticate_user!

  def new
    if user_signed_in?
      @profile = current_user.build_profile(profile_params)
      
      if @profile.save
        render json: @profile, status: :created
      else
        render json: { errors: @profile.errors.full_messages }, status: :unprocessable_entity
      end
    else
      render json: { message: 'Authentication error' }, status: :unauthorized
    end
  end

  def show
    @profile = current_user.profile
    render json: @profile
  end

  def edit
    @profile = current_user.profile
    render json: @profile
  end
  
  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to user_api_v1_profile_path, notice: 'Profile updated successfully.'
    else
      render :edit
    end
  end
  
  private

  def profile_params
    params.permit(:first_name, :last_name, :phone, :street_address, :city, :county)
  end

  def respond_with_success
    render json: {
      status: { code: 200, message: "Profile created successfully." },
      profile: @profile
    }, status: :ok
  end

  def respond_with_failure(resource)
    render json: {
      status: { code: 422, message: "Profile couldn't be created. #{resource.errors.full_messages.to_sentence}" }
    }, status: :unprocessable_entity
  end

  def respond_with_authentication_error
    render json: {
      status: { code: 401, message: "Unauthorized. Please sign in." }
    }, status: :unauthorized
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def new
    @profile = current_user.profile || current_user.build_profile
  end

  def create
    @profile = current_user.profile || current_user.build_profile(profile_params)

    if @profile.save
      redirect_to user_profile_path, notice: 'Profile created successfully.'
    else
      render :new
    end
  end

  def show
    @user = current_user
    @profile = current_user.profile
    @orders = current_user.orders
    unless @profile
      redirect_to new_profile_path, alert: "Please complete your profile first."
    end
  end

  def edit
    @profile = current_user.profile
  end
  
  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to user_profile_path, notice: 'Profile updated successfully.'
    else
      render :edit
    end
  end
  
  private

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :phone, :street_address, :city, :county)
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/edit.haml
= stylesheet_link_tag "form"
= stylesheet_link_tag "buttons"

- provide(:title, "Editing your profile")

.container
  .profile-form
    %h3.form-header Edit your profile data
    = form_for(@profile,data: { turbo: false }) do |f| 
      .form-field
        = f.text_field :first_name, placeholder: 'First name *'
        = f.text_field :last_name, placeholder: 'Last name *'
        = f.text_field :phone, placeholder: 'Phone *' 
        - if current_user.role == 'customer'
          = f.text_field :street_address, placeholder: 'Street Address *'
          = f.text_field :city, placeholder: 'City *'
          = f.text_field :county, placeholder: 'County *'
        = f.submit "Update Profile", class: "button"

app/views/profiles/new.haml
= stylesheet_link_tag "form"
= stylesheet_link_tag "buttons"

- provide(:title, "Create a profile")

.container
  %h2.form-header Create your profile
  .profile-form
    = form_for(@profile) do |f|
      - if @profile.errors.any?
        .alert.alert-danger
          %ul
            - @profile.errors.full_messages.each do |message|
              %li= message
      .form-field
        = f.text_field :first_name, placeholder: 'First name *'
        = f.text_field :last_name, placeholder: 'Last name *'
        = f.text_field :phone, placeholder: 'Phone *'
        - if current_user.role == "customer"
          = f.text_field :street_address, placeholder: 'Street Address *'
          = f.text_field :city, placeholder: 'City *'
          = f.text_field :county, placeholder: 'County *'
        = f.submit "Complete Profile", class: "btn button"

app/views/profiles/show.haml
= stylesheet_link_tag "profile"
= stylesheet_link_tag "buttons"

- provide(:title, "#{ @profile.first_name }")

.container
  .profile-details
    - if @profile
      %h2 
        Hello, 
        .profile-name=@profile.first_name 
        !
      %p
        %strong First Name: 
        = @profile.first_name
      %p
        %strong Last Name: 
        = @profile.last_name
      %p
        %strong Phone: 
        = @profile.phone
      - if current_user.role =="customer"
        %p
          %strong Street Address: 
          = @profile.street_address
        %p
          %strong City: 
          = @profile.city
        %p
          %strong County: 
          = @profile.county
        %p 
          %strong Token de Autentificare:
          = @auth_token

    - else
      %p You don't have a profile yet.

  .account-details
    - if @user 
      %h5
        %strong
          Account details 
      %p
        %strong Email: 
        = current_user.email
        %br/
        = link_to 'Change password', edit_user_registration_path, class: "link"
    - else 
      %p You don't have an account.

  .edit-actions
    = link_to 'Edit Profile', edit_profile_path(@profile), class: 'btn button btn-primary'
    = link_to "Cancel my account", registration_path(current_user), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class: "link"

    