config/routes.rb
Rails.application.routes.draw do
  get 'current_user/index'
  
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  root "home#index"
  get "/about", to: "static_pages#about", as: :about
  get "/blog", to: "static_pages#blog"
  get "/contacts", to: "static_pages#contacts"
  get "/services", to: "static_pages#services"
  get '/services/product_filter_service', to: 'product_filter_service#filter'
  get 'profile', to: 'profiles#show', as: :user_profile
  get 'profile_updated', to: 'profiles#updated', as: :profile_updated
  get 'add_to_cart/:product_id', to: 'orders#create', as: 'add_to_cart'
  get 'cart', to: 'orders#cart'
  post 'complete_order', to: 'orders#complete_order', as: 'complete_order'
  get 'completed_orders', to: 'orders#completed_orders', as: 'completed_orders'
  get "orders_page", to: "orders#orders_page", as: "orders_page"
  get 'admin/orders', to: 'admin#orders', as: 'admin_orders'
  
  resources :orders, only: [:show] do
    collection do
      delete 'remove_from_cart/:order_item_id', action: :remove_from_cart, as: :remove_from_cart
    end
  end

  resources :products
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :orders do
    member do
      patch :handle, to: 'orders#handle'
    end
  end

  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: { registrations: 'api/v1/users/registrations', sessions: 'api/v1/users/sessions' }    
      resources :products
      resources :profiles, only: [:new, :create, :edit, :update]
      resources :orders do
        member do
          patch :handle, to: 'orders#handle'
          post :remove_from_cart, to: 'orders#remove_from_cart'
          post :complete_order, to: "orders@complete_orders"
        end
      end
      resources :admin do
        collection do
          get :all_users
        end
      end
      get '/services/product_filter_service', to: 'product_filter_service#filter'
      get 'profile', to: 'profiles#show', as: :user_profile
      get 'profile/new', to: "profiles#new", as: "new_profile"
      get 'profile_updated', to: 'profiles#updated', as: :profile_updated
      post 'add_to_cart', to: 'orders#create', as: 'add_to_cart'
      get 'cart', to: 'orders#cart'
      post 'complete_order', to: 'orders#complete_order', as: 'complete_order'
      get 'completed_orders', to: 'orders#completed_orders', as: 'completed_orders'
      get "orders_page", to: "orders#orders_page", as: "orders_page"
      get 'admin/orders', to: 'admin#orders', as: 'admin_orders'
      root "home#index"
    end
  end


end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many  :order_items, dependent: :destroy
  has_many  :products, through: :order_items

  validates :user_id, presence: true
  validates :order_date, presence: true
  validates :status, presence: true
  validate  :completed_order_date_validity

  enum status: {
    pending: 0,
    processing: 1,
    completed: 2,
    handled: 3
  }

  def total_price 
    order_items.sum { |item| item.product.price * item.quantity }  
  end

  private

  def completed_order_date_validity
    if completed? && completed_order_date.blank?
      errors.add(:completed_order_date, "must be present for completed orders")
    end
  end

end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < Api::V1::ApplicationController
  before_action :authenticate_user!
  before_action :find_products, only: [:create]

  def create
    order = current_user.orders.build(order_date: Date.today, status: 'pending')
  
    @products.each do |product|
      existing_order_item = order.order_items.find_by(product: product)
      
      if existing_order_item
        existing_order_item.quantity += 1
      else
        existing_order_item = order.order_items.build(product: product, quantity: 1, out_of_stock: false)
      end
    end
  
    if order.save
      render json: { message: 'Order created successfully.', cart_items: order.order_items }, status: :created
    else
      render json: { error: 'Failed to create order.' }, status: :unprocessable_entity
    end
  end
  
  def handle
    @order = Order.find(params[:id])
    
    if @order.update(status: "handled")
      render json: { message: "Order has been marked as handled." }, status: :ok
    else
      render json: { error: "Failed to update order status." }, status: :unprocessable_entity
    end
  end
  
  def cart
    cart_orders = current_user.orders.includes(:order_items, :products).where(status: 'pending')
    
    cart_items = cart_orders.flat_map(&:order_items)
    cart_product_count = cart_items.sum(&:quantity)
    
    render json: {
      cart_items: cart_items,
      cart_product_count: cart_product_count
    }, status: :ok
  end
  
  def remove_from_cart
    @order_item = OrderItem.find(params[:order_item_id])

    if @order_item.quantity > 1
      @order_item.quantity -= 1
      @order_item.save
    else
      @order_item.destroy
    end

    response_message = @order_item.destroyed? ? 'Product removed from cart.' : 'Product quantity decreased in cart.'
    cart_items = current_user.orders.where(status: 'pending').flat_map(&:order_items)
    cart_owner = current_user
    cart_product_count = cart_items.sum(&:quantity)
    
    render json: {
      message: response_message,
      cart_items: cart_items,
      cart_owner: cart_owner,
      cart_product_count: cart_product_count
    }, status: :ok
  end

  def complete_order
    @user_processing_orders = current_user.orders.includes(:order_items, :products).where(status: 'processing')
  
    if request.post?
      @user_processing_orders.update(status: 'completed', completed_order_date: Date.today)
      completed_orders = current_user.orders.where(status: 'completed')
  
      render json: { message: 'Orders completed successfully.'}, status: :ok
    else
      render json: { error: 'Invalid request.' }, status: :unprocessable_entity
    end
  end
  
  def completed_orders
    @orders = current_user.orders.where(status: 'completed')
    render json: @orders, include: :order_items
  end

  def orders_page
    @orders = current_user.orders.where(status: ['pending', 'processing', 'completed'])
    render json: @orders, include: :order_items
  end

  def show
    @order = Order.find(params[:id])
    render json: @order
  end

  private

  def find_products
    puts "Params: #{params.inspect}"
    @products = Product.where(id: params[:product_ids])
    puts "Found products: #{@products}"
  end

  def order
    existing_orders = current_user.orders.where(status: ['pending', 'processing'])

    if existing_orders.empty?
      @order = current_user.orders.create(order_date: Date.today, status: 'pending')
    else
      @order = existing_orders.first
    end
  end

  def mark_order_item_as_out_of_stock(product)
    orders_to_update = Order.processing.includes(:order_items).where(order_items: { product: product })

    orders_to_update.each do |order|
      order_item = order.order_items.find_by(product: product)
      order_item&.update(out_of_stock: true)
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    @product = Product.find(params[:product_id])
    order
    begin
      redirect_to root_path, notice: 'Product not found.' unless @product
  
      existing_order_item = @order.order_items.find_by(product: @product)
  
      if existing_order_item
        existing_order_item.quantity += 1
        notice_message = existing_order_item.save ? 'Product added to cart.' : 'Error updating cart.'
        redirect_to root_path, notice: notice_message
      else
        @order_item = @order.order_items.new(product: @product, quantity: 1, out_of_stock: false)
        notice_message = @order_item.save ? 'Product added to cart.' : 'Error adding product to cart.'
        redirect_to root_path, notice: notice_message
      end
    rescue => error
      redirect_to root_path, notice: "Error adding product to cart: #{error.message}"
    end
  end
   
  def handle
    @order = Order.find(params[:id])
    @order.update(status: "handled")
    redirect_to admin_orders_path, notice: "Order has been marked as handled."
  end
  
  def cart
    @orders = current_user.orders.includes(:order_items, :products).where(status: ['pending', 'processing'])
    @orders.update_all(status: 'processing') 
  end

  def remove_from_cart
    @order_item = OrderItem.find(params[:order_item_id])
    
    if @order_item.quantity > 1
      @order_item.quantity -= 1
      @order_item.save
    else
      @order_item.destroy
    end    
  
    if request.referrer == root_path
      redirect_to root_path, notice: 'Product quantity decreased in cart.'
    else
      redirect_to cart_path, notice: 'Product quantity decreased in cart.'
    end
  end
  
  def complete_order
    @user_processing_orders = current_user.orders.includes(:order_items, :products).where(status: 'processing')
  
    if request.post?
      @user_processing_orders.update(status: 'completed', completed_order_date: Date.today)
      redirect_to completed_orders_path, notice: 'Orders completed successfully.'
    end
  end
  
  def completed_orders
    @orders = current_user.orders.where(status: 'completed')
  end

  def orders_page
    @orders = current_user.orders.where(status: ['processing', 'completed'])
  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def order
    existing_orders = current_user.orders.where(status: ['pending', 'processing'])

    if existing_orders.empty?
      @order = current_user.orders.create(order_date: Date.today, status: 'pending')
    else
      @order = existing_orders.first
    end
  end

  def mark_order_item_as_out_of_stock(product)
    orders_to_update = Order.processing.includes(:order_items).where(order_items: { product: product })

    orders_to_update.each do |order|
      order_item = order.order_items.find_by(product: product)
      order_item&.update(out_of_stock: true)
    end
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/cart.haml
= stylesheet_link_tag "cart_page"
= stylesheet_link_tag "products_images"

- provide(:title, "Cart")

.container
  .cart-header.mb-4
    %h1 Cart
  
  .cart-details
    - @orders.each do |order|
      
      .cart-items
        - order.order_items.each do |item|
          .cart-item{ class: (item.product.category == "drink" ? 'cart-drink-photo' : '')}
            .cart-image
              - if item.product.photo.attached?
                = image_tag item.product.photo
              - else
                %p No photo available
            .food-details
              %h5.price
                $#{ item.product.price }
              %h6 
                = item.product.title
              %p.description
                = truncate(item.product.description, length: 70) + link_to(" View more", product_path(item.product), class: "view-more-link")
              %p.quantity
                Quantity:
                = item.quantity
              %a.remove{ href: remove_from_cart_orders_path(order_item_id: item.id), 'data-confirm': 'Are you sure you want to remove this product from your cart?', 'data-method': 'delete', 'data-bs-toggle': "tooltip", 'data-bs-placement': "bottom", 'data-bs-title': "Remove from cart" }
                %i.bi.bi-trash-fill
      .order-status
        %h4 
          %strong Order details
        %p 
          Total Price: 
          %strong $#{ order.total_price }
        %p 
          %strong Status: 
          %span= order.status
        = link_to 'Order', complete_order_path, method: :post, class: 'btn btn-success'

app/views/orders/completed_orders.haml
= stylesheet_link_tag "orders"
= stylesheet_link_tag "buttons"

- provide(:title, "Completed Orders")

.container
  .order-header
    %h1 Your Orders
  
  .order-details
    - @orders.each do |order|
      - if notice.present?
        .notice= notice
      .order-item
        .order-status 
          %strong Order ID:
          = order.id
          %br/
          %strong Status:
          %span{ :class => ("completed" if order.status == 'completed' ) }= order.status
    
        .order-products
          %p
            %strong Products:
          %ol
            - order.order_items.each do |item|
              %li
                = item.product.title
                %strong $#{ item.product.price * item.quantity }
                = "q: #{  item.quantity }"
        = link_to 'View Order', order_path(order), class: "link"

  = link_to 'Back', :back, class: "back-link"
      

app/views/orders/orders_page.haml
= stylesheet_link_tag "orders"
= stylesheet_link_tag "buttons"

- provide(:title, "Orders")

.container
  .order-header
    %h1 Your Orders
  
  .order-details
    - @orders.each do |order|
      .order-item
        .order-status 
          %strong Order ID:
          = order.id
          %br/
          %strong Status:
          %span{ :class => ("completed" if order.status == 'completed' ) }= order.status
    
        .order-products
          %p
            %strong Products:
          %ol
            - order.order_items.each do |item|
              %li
                = item.product.title
                %strong $#{ item.product.price * item.quantity }
                = "q: #{  item.quantity }"
        = link_to 'View Order', order_path(order), class: "link"

  = link_to 'Back', :back, class: "back-link"
      

app/views/orders/show.haml
= stylesheet_link_tag "orders"
= stylesheet_link_tag "buttons"

- provide(:title, "Order " + "#" + "#{ @order.id }")

.container
  .order-item
    .order-header
      %h1 
        %strong 
        Order #
        = @order.id
      %p
        %strong Status:
        %span= @order.status
      .order-products
        %p
          %strong Products:
        %ol
          - @order.order_items.each do |item|
            %li
              = item.product.title
              = item.product.price
  = link_to 'Back', :back, class: "back-link"