config/routes.rb
Rails.application.routes.draw do
  get 'current_user/index'
  
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  root "home#index"
  get "/about", to: "static_pages#about", as: :about
  get "/blog", to: "static_pages#blog"
  get "/contacts", to: "static_pages#contacts"
  get "/services", to: "static_pages#services"
  get '/services/product_filter_service', to: 'product_filter_service#filter'
  get 'profile', to: 'profiles#show', as: :user_profile
  get 'profile_updated', to: 'profiles#updated', as: :profile_updated
  get 'add_to_cart/:product_id', to: 'orders#create', as: 'add_to_cart'
  get 'cart', to: 'orders#cart'
  post 'complete_order', to: 'orders#complete_order', as: 'complete_order'
  get 'completed_orders', to: 'orders#completed_orders', as: 'completed_orders'
  get "orders_page", to: "orders#orders_page", as: "orders_page"
  get 'admin/orders', to: 'admin#orders', as: 'admin_orders'
  
  resources :orders, only: [:show] do
    collection do
      delete 'remove_from_cart/:order_item_id', action: :remove_from_cart, as: :remove_from_cart
    end
  end

  resources :products
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :orders do
    member do
      patch :handle, to: 'orders#handle'
    end
  end

  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: { registrations: 'api/v1/users/registrations', sessions: 'api/v1/users/sessions' }    
      resources :products
      resources :profiles, only: [:new, :create, :edit, :update]
      resources :orders do
        member do
          patch :handle, to: 'orders#handle'
          post :remove_from_cart, to: 'orders#remove_from_cart'
          post :complete_order, to: "orders@complete_orders"
        end
      end
      resources :admin do
        collection do
          get :all_users
        end
      end
      get '/services/product_filter_service', to: 'product_filter_service#filter'
      get 'profile', to: 'profiles#show', as: :user_profile
      get 'profile/new', to: "profiles#new", as: "new_profile"
      get 'profile_updated', to: 'profiles#updated', as: :profile_updated
      post 'add_to_cart', to: 'orders#create', as: 'add_to_cart'
      get 'cart', to: 'orders#cart'
      post 'complete_order', to: 'orders#complete_order', as: 'complete_order'
      get 'completed_orders', to: 'orders#completed_orders', as: 'completed_orders'
      get "orders_page", to: "orders#orders_page", as: "orders_page"
      get 'admin/orders', to: 'admin#orders', as: 'admin_orders'
      root "home#index"
    end
  end


end

app/views/layouts/_footer.haml
.footer
  %p Assigment 3
  %p Oana Istoc - Ruby on Rails Internship
  = link_to "https://www.wolfpack-digital.com/", target: "_blank" do
    = image_tag("wd.png", alt: "Logo")
  

app/views/layouts/_header.haml
= javascript_include_tag 'dropdown'

.navbar{ class: current_page?(root_path) ? nil : 'not-home' }
  .left-logo 
    = link_to root_path do
      = image_tag("logo.png", alt: "Logo")

    %a{ href: "#" }
      %p 
        Eureka 
        %br 
        Coffee  
  
  .right-menu 
    = link_to "Home", root_path
    %i.bi.bi-circle-fill
    = link_to "About", about_path
    %i.bi.bi-circle-fill
    = link_to "Services", "/services"
    %i.bi.bi-circle-fill
    = link_to "Blog", "/blog"
    %i.bi.bi-circle-fill
    = link_to "Contacts", "/contacts"
    - if user_signed_in?
      %i.bi.bi-circle-fill
      .my-profile
        %p
          = "#{current_user.role} profile"
          = current_user.profile.first_name if current_user.profile
          %i#arrow.bi.bi-caret-down-fill
        .dropdown-content#dropdown-content{ class: current_page?(root_path) ? nil : 'not-home' }
          - if current_user.role == 'customer' 
            .cart
              = link_to 'Cart', cart_path
            .orders
              = link_to 'Orders', orders_page_path
          -elsif current_user.role == "admin"
            .products
              = link_to "Products", products_path
            .orders
              = link_to "Orders", admin_orders_path	
          .profile 
            = link_to 'View Profile', user_profile_path
          .sign-out
            = link_to "Sign out", destroy_user_session_path, method: :delete, 'data-turbo-method': :delete    

    - else
      %i.bi.bi-circle-fill
      = link_to "Sign up", new_user_registration_path
      %i.bi.bi-circle-fill
      = link_to "Log in", new_user_session_path
   

app/views/layouts/application.haml
<!DOCTYPE html>
%html(lang="en")
  %head
    %meta(charset="UTF-8")/
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")/
    %title= full_title(yield(:title))
    %link{ href: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css", rel: "stylesheet", integrity: "sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9", crossorigin: "anonymous" }
    %link{ href: "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css", rel: "stylesheet" }
    %link{ rel: "preconnect", href: "https://fonts.googleapis.com" }
    %link{ rel: "preconnect", href: "https://fonts.gstatic.com", crossorigin: true }
    %link{ href: "https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap", rel: "stylesheet" }
    = stylesheet_link_tag "toastr.min.css"
    = stylesheet_link_tag "application", "data-turbo-track" => "reload"
    = stylesheet_link_tag "nouislider.min", media: "all"
    = javascript_include_tag "nouislider.min"
    = javascript_include_tag "toastr.min"
    = javascript_include_tag "application"

  %body{  style: "font-family: 'Poppins';" } 
    .header
      = render "layouts/header"
    .main
      .notices{ style: 'display: none' }
        %p.notice(data-notice="#{j(notice)}")
        %p.alert(data-alert="#{j(alert)}")

      = yield
      
    .footer
      = render "layouts/footer"